### ISSUE TITLE
Usage with React

### ISSUE THREAD

**Issue by grgmyr** [evantahler/actionhero-client#13]
Hi,

I was trying to have my React application connect to Action Hero server. I tried using both the javascript file generated (in https://github.com/evantahler/actionhero-tutorial/tree/master/public folder) and the action hero client (https://github.com/evantahler/actionhero-client). Can you provide a simple example of how a react component can talk to the action hero server?

Thank you!

**Comment by grgmyr** [comment]
Sorry, not an issue, have got it working now.

**Comment by evantahler** [comment]
Cool.
Note that this project is for node.js - node.js serers, not for the browser.
