### ISSUE TITLE
connection object is wrong in actionhero client 

### ISSUE THREAD

**Issue by sanmoy27** [evantahler/actionhero-client#14]
var ActionheroClient = require("actionhero-client");
var client = new ActionheroClient();
				client.connect({
				  host: "127.0.0.1", // first, I tried with just host
				  port: "8080",      // and port
				  url: "http://localhost:8080" 
				},function(err, details) {
				  console.log("connect")
				  if(err != null){
					console.log(err)
				  }else{
					console.log("connected "+details.status);
					client.roomAdd(channel);
					client.on("say", function(msg){
						console.log(msg);
					});
				  }
				});

**Comment by sanmoy27** [comment]
Error is: 

/home/ubuntu/project/project/node_modules/actionhero-client/lib/actionhero-client.js:96
        self.connectCallback(null, self.lastLine.welcome)
                                                ^

TypeError: Cannot read property 'welcome' of null
    at /home/ubuntu/project/project/node_modules/actionhero-client/lib/actionhero-client.js:96:49
    at /home/ubuntu/project/project/node_modules/actionhero-client/lib/actionhero-client.js:263:5
    at Timeout._onTimeout (/home/ubuntu/project/project/node_modules/actionhero-client/lib/actionhero-client.js:206:11)
    at ontimeout (timers.js:372:18)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by evantahler** [comment]
This is not the proper use of this tool.  This is not an HTTP of WS client
