### ISSUE TITLE
connection options not correct in the docs

### ISSUE THREAD

**Issue by heavyk** [evantahler/actionhero-client#5]
I'll be willing to do a PR to fix them or the code... I just don't know what needs to be fixed. so, here's the lowdown of what works:

```js
client = new ActionheroClient({
  host: "127.0.0.1", // first, I tried with just host
  port: "8880",      // and port
  // later, I noticed after looking at the source, that url wasn't rebuilt, so I added the url 
  url: "http://localhost:8880" 
})
// connected OK
client.connect(function(err, details) {
  console.log("connect", arguments)
  if(err != null){
    console.log(err)
  }else{
    console.log("connected "+details.status)
  }
})
```

(now that I think about it, my evaluation may be slightly wrong... I've only tested with the actionheroClient.js generated in the latest version of AH) so..

1. the docs say to pass only host and port to the `connect` function not the constructor. func only accepts a callback.
2. if only `host` and `port` are passed to the constructor, it'll still fail to connect because the the url is what is passed to Primus' constructor
3. url isn't mentioned anywhere. I assume it was supposed to be generated

-----
P.S. I just want to say, ** super awesome library! ** seriously! absolutely has reduced my dev time a whole bunch and a great concept... in addition, I've found some other bugs and I'm tracking them down still... they are the following:
1. infinite restarting loop in dev mode when the code gets updated rapidly
2. initializers not calling start when above 400. (though, this may be my fault cause as I recall I may have a generator in there, but it's happening to me on the sequelize plugin right now. I changed the number in the code to continue working but I'll get to the bottom of it soon)
3. in latest chromium the navbar on top of the docs doesn't show

cheers

**Comment by evantahler** [comment]
Can you share where in the docs it says to use host/port (I can't find it)?  `url` is the correct option, and that is sourced automatically from `api.config.servers.websocket.clientUrl`.  When the server is booted and the client JS generated, that url should be included as a default.

`ActionheroClient` does take [2 inputs](https://github.com/evantahler/actionhero/blob/master/client/actionheroClient.js#L1), `options` and `client`.  So `new ActionheroClient({url: 'https://....'}) ` is valid.

Please open separate issues for the other problems!

**Comment by evantahler** [comment]
OH! 

This library is NOT the same as the websocket library that is generated from within actionhero.  This is a srever-server library that works via TCP.

**Comment by evantahler** [comment]
https://github.com/evantahler/actionhero-client/commit/832a53a1f8c3178147d747ff9c6782205078484d

**Comment by heavyk** [comment]
OH! oki then :)

sounds good. I'll investigate the others soon. thanks!

(btw, actually, I found out about this library from the AH docs here: http://localhost:4000/docs/servers/socket.html#client-suggestions - after pasting the url, I see now that it's in reference to the socket connections, instead of -web- socket connections - doh!)

thanks again!
